MMM.boardConfig = [{
  id: "sq-0-0",
}, {
  id: "sq-0-1",
  styles: "xtra-margin-left"
}, {
  id: "sq-0-2",
  styles: "xtra-margin-left"
}, {
  id: "sq-0-3",
  styles: "xtra-margin-left"
}, {
  id: "sq-0-4",
  styles: "xtra-margin-left"
}, {
  id: "sq-1-0",
  styles: "xtra-margin-top"
}, {
  id: "sq-1-1",
  styles: "xtra-margin"
}, {
  id: "sq-1-2",
  styles: "xtra-margin"
}, {
  id: "sq-1-3",
  styles: "xtra-margin"
}, {
  id: "sq-1-4",
  styles: "xtra-margin"
}, {
  id: "sq-2-0",
  styles: "xtra-margin-top"
}, {
  id: "sq-2-1",
  styles: "xtra-margin"
}, {
  id: "sq-2-2",
  styles: "xtra-margin"
}, {
  id: "sq-2-3",
  styles: "xtra-margin"
}, {
  id: "sq-2-4",
  styles: "xtra-margin"
}, {
  id: "sq-3-0",
  styles: "xtra-margin-top"
}, {
  id: "sq-3-1",
  styles: "xtra-margin"
}, {
  id: "sq-3-2",
  styles: "xtra-margin"
}, {
  id: "sq-3-3",
  styles: "xtra-margin"
}, {
  id: "sq-3-4",
  styles: "xtra-margin"
}, {
  id: "sq-4-0",
  styles: "xtra-margin-top"
}, {
  id: "sq-4-1",
  styles: "xtra-margin"
}, {
  id: "sq-4-2",
  styles: "xtra-margin"
}, {
  id: "sq-4-3",
  styles: "xtra-margin"
}, {
  id: "sq-4-4",
  styles: "xtra-margin"
}];